### PR TITLE
feat: pulumi

### PR DESCRIPTION
**Pull request by lmilbaum**

### CODE REVIEW

**Comment by lmilbaum** [comment]
> @lmilbaum what is the context for adding pulumi here? Can you describe a bit the purpose for the helper image?
> 
> Just to know if it make sense also to handle related providers in the same way (pulumi-aws, pulumi-azure,...)

The helper container image is being used in the auto-pe efforts. The tech stack is already large and it is growing every day.  Running our commands with the container image saves us the need to install the tools in our environments (DEV/CI/PROD).

Does that answer your question?

**Comment by adrianriobo** [comment]
Yeah I see, ok sound good to me, `pulumi` will use same approach as it is used by `terraform` within the plugins management.

**Review by adrianriobo — APPROVED** [review]

**Comment by adrianriobo** [comment]
off-topic question is renovate capable to check content on `.tool-versions` file?

**Comment by lmilbaum** [comment]
> off-topic question is renovate capable to check content on `.tool-versions` file?

Yup. The file is used by asdf which is renovate friendly tool.

**Pull request merged**
